# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
